configuration {
    show-icons:          true;
    icon-theme:          "hicolor";
    hover-select:        true;
    me-select-entry:     "";
    me-accept-entry:     "MousePrimary";
}

@theme "themes/wallpaper"
