# Disable the default Hyprland splash text at the bottom of the screen
splash = false
ipc = true

# Main display
wallpaper {
    monitor = eDP-1
    path = /home/kylle/archdatback/wallpaper/cute-town-dark.png
    fit_mode = cover
}

# Fallback for any external monitors you connect later
wallpaper {
    monitor = 
    path = /home/kylle/archdatback/wallpaper/cute-town-dark.png
    fit_mode = cover
}
